version: '3.1'

services:
    mysql:
        container_name: mysql_db
        command: --default-authentication-plugin=mysql_native_password

        image: mysql
        ports:
            - 3306:3306

        environment:
            MYSQL_ROOT_PASSWORD: '123456'
            MYSQL_DATABASE: 'task'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'task123'
